version: 0.2
phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - export FLASK_APP=hello.py
      - echo Building the Docker image...   
      - flask run
  post_build:
    commands:
      - echo Build completed on `date`